# Generated by Django 5.1.4 on 2025-09-23 15:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('news', 'News'), ('publications', 'Publications'), ('events', 'Events'), ('gapag_news', 'GAPAG News'), ('gapag_events', 'GAPAG Events')], max_length=50)),
                ('title_en', models.CharField(max_length=300)),
                ('title_ge', models.CharField(max_length=300)),
                ('content_en', models.TextField()),
                ('content_ge', models.TextField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
            ],
            options={
                'unique_together': {('language', 'key')},
            },
        ),
    ]
