# Generated by Django 5.1.4 on 2025-09-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicpost',
            name='additional_image1',
            field=models.ImageField(blank=True, null=True, upload_to='posts/additional/'),
        ),
        migrations.AddField(
            model_name='dynamicpost',
            name='additional_image2',
            field=models.ImageField(blank=True, null=True, upload_to='posts/additional/'),
        ),
        migrations.AddField(
            model_name='dynamicpost',
            name='additional_image3',
            field=models.ImageField(blank=True, null=True, upload_to='posts/additional/'),
        ),
        migrations.AddField(
            model_name='dynamicpost',
            name='image1_caption_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicpost',
            name='image1_caption_ge',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicpost',
            name='image2_caption_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicpost',
            name='image2_caption_ge',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicpost',
            name='image3_caption_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicpost',
            name='image3_caption_ge',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='dynamicpost',
            name='main_image',
            field=models.ImageField(null=True, upload_to='posts/main/'),
        ),
    ]
